/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainDashboardRouteRouteImport } from './routes/_main/dashboard/route'
import { Route as MainDashboardIndexRouteImport } from './routes/_main/dashboard/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MainDashboardItemsRouteImport } from './routes/_main/dashboard/items'
import { Route as MainDashboardImportRouteImport } from './routes/_main/dashboard/import'
import { Route as MainDashboardDiscoverRouteImport } from './routes/_main/dashboard/discover'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainDashboardRouteRoute = MainDashboardRouteRouteImport.update({
  id: '/_main/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MainDashboardIndexRoute = MainDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainDashboardRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainDashboardItemsRoute = MainDashboardItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => MainDashboardRouteRoute,
} as any)
const MainDashboardImportRoute = MainDashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => MainDashboardRouteRoute,
} as any)
const MainDashboardDiscoverRoute = MainDashboardDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => MainDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof MainDashboardRouteRouteWithChildren
  '/dashboard/discover': typeof MainDashboardDiscoverRoute
  '/dashboard/import': typeof MainDashboardImportRoute
  '/dashboard/items': typeof MainDashboardItemsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/dashboard/': typeof MainDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/discover': typeof MainDashboardDiscoverRoute
  '/dashboard/import': typeof MainDashboardImportRoute
  '/dashboard/items': typeof MainDashboardItemsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/dashboard': typeof MainDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main/dashboard': typeof MainDashboardRouteRouteWithChildren
  '/_main/dashboard/discover': typeof MainDashboardDiscoverRoute
  '/_main/dashboard/import': typeof MainDashboardImportRoute
  '/_main/dashboard/items': typeof MainDashboardItemsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_main/dashboard/': typeof MainDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/items'
    | '/api/auth/$'
    | '/login'
    | '/register'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/items'
    | '/api/auth/$'
    | '/login'
    | '/register'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_main/dashboard'
    | '/_main/dashboard/discover'
    | '/_main/dashboard/import'
    | '/_main/dashboard/items'
    | '/api/auth/$'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_main/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainDashboardRouteRoute: typeof MainDashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/dashboard/': {
      id: '/_main/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof MainDashboardIndexRouteImport
      parentRoute: typeof MainDashboardRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/dashboard/items': {
      id: '/_main/dashboard/items'
      path: '/items'
      fullPath: '/dashboard/items'
      preLoaderRoute: typeof MainDashboardItemsRouteImport
      parentRoute: typeof MainDashboardRouteRoute
    }
    '/_main/dashboard/import': {
      id: '/_main/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof MainDashboardImportRouteImport
      parentRoute: typeof MainDashboardRouteRoute
    }
    '/_main/dashboard/discover': {
      id: '/_main/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof MainDashboardDiscoverRouteImport
      parentRoute: typeof MainDashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainDashboardRouteRouteChildren {
  MainDashboardDiscoverRoute: typeof MainDashboardDiscoverRoute
  MainDashboardImportRoute: typeof MainDashboardImportRoute
  MainDashboardItemsRoute: typeof MainDashboardItemsRoute
  MainDashboardIndexRoute: typeof MainDashboardIndexRoute
}

const MainDashboardRouteRouteChildren: MainDashboardRouteRouteChildren = {
  MainDashboardDiscoverRoute: MainDashboardDiscoverRoute,
  MainDashboardImportRoute: MainDashboardImportRoute,
  MainDashboardItemsRoute: MainDashboardItemsRoute,
  MainDashboardIndexRoute: MainDashboardIndexRoute,
}

const MainDashboardRouteRouteWithChildren =
  MainDashboardRouteRoute._addFileChildren(MainDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainDashboardRouteRoute: MainDashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
